<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.2" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.2" />
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Itura.Analytics.Domain\Itura.Analytics.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Itura.SharedKernel\Itura.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\Shared\Itura.Contracts\Itura.Contracts.csproj" />
  </ItemGroup>
</Project>
